# Base image.]
FROM node:22.7.0-alpine

# Set evironment variables.
ENV LANG=C.UTF-8

# Set up working directory.
WORKDIR /app

# Copy package.json file to working directory.
COPY /src/package.json .

# Install packages.
RUN npm install
#RUN yarn

# Copy directory.
COPY /src .

# Build.
RUN npm run build
#RUN yarn build

# Document exposed port.
EXPOSE ${NEXTJS_PORT}

# Start app.
CMD ["npm", "run", "start"]
#CMD　["yarn", "start"]